return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  branch = 'main',
  config = function()
    require('nvim-treesitter').setup()
  end,
  opts = {
    ensure_installed = {
      'bash',
      'c_sharp',
      'caddy',
      'css',
      'csv',
      'desktop',
      'diff',
      'dockerfile',
      'editorconfig',
      'gdscript',
      'gdshader',
      'git_config',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'html',
      'ini',
      'javascript',
      'jsdoc',
      'json',
      'json5',
      'jsonc',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'php',
      'printf',
      'prisma',
      'properties',
      'python',
      'robots',
      'scss',
      'sql',
      'ssh_config',
      'toml',
      'tsx',
      'typescript',
      'xml',
      'yaml',
      'zig',
    },
    sync_install = false,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
